version: '3.9'
services:
  db:
    image: postgres:latest
    container_name: db_cli
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: something
    networks:
      - network
    ports:
      - 54320:5432
    volumes:
      - db_data:/var/lib/postgresql/data
  # zookeeper:
  #   image: wurstmeister/zookeeper:3.4.6
  #   restart: always
  #   expose:
  #     - "2181"

  # kafka:
  #   depends_on:
  #     - zookeeper
  #   environment:
  #     KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
  #     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
  #     KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
  #     KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  #     KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
  #   hostname: kafka
  #   image: wurstmeister/kafka:2.11-2.0.0
  #   restart: always
  #   ports:
  #     - "9092:9092"
  #   expose:
  #     - "9093"
  #   links:
  #     - zookeeper:zookeeper


networks:
  network:
    driver: bridge

volumes:
  db_data: